name: Tests

env:
  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}
  POLYGON_MUMBAI_RPC_PROVIDER: ${{ secrets.POLYGON_MUMBAI_RPC_PROVIDER }}
  POLYGON_MAINNET_RPC_PROVIDER: ${{ secrets.POLYGON_MAINNET_RPC_PROVIDER }}
  POLYGONSCAN_API_KEY: ${{ secrets.POLYGONSCAN_API_KEY }}
  COINMARKETCAP_API_KEY:  ${{ secrets.COINMARKETCAP_API_KEY }}
on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Generate typechain
        run: yarn hardhat typechain

      - name: Run coverage
        run: yarn hardhat coverage
