name: Tests

env:
  WALLET_PRIVATE_KEY: ${{ secrets.WALLET_PRIVATE_KEY }}

on:
  push:
    branches: 
      - main
  pull_request:

jobs:
  unit-tests:
    name: Unit tests
    runs-on: ubuntu-latest

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Set up node
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install

      - name: Compile contracts and run coverage
        run: yarn hardhat coverage
